version: "3"
services:
    #mongodb service
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    #mounting volumes for data persistence
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'      
  #server service
  parking_system_server:
    build: .
    environment:
      - PORT=8080
      - DB_HOST=mongodb
      - DB_NAME=parkingSystem
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
  
